### ISSUE TITLE
Failed to script Map

### ISSUE THREAD

**Issue by CenteredAxis** [Valalol/Star-Citizen-Navigation#8]
**Describe the bug**
Attempting to run the map.exe I get the following error:
`Logs.csv file found !
Start plotting ...
Traceback (most recent call last):
  File "Map.py", line 32, in <module>
  File "tkinter\__init__.py", line 2080, in wm_iconbitmap
_tkinter.TclError: bitmap "Images/icon.ico" not defined
[12840] Failed to execute script Map`

**To Reproduce**
1. Go to main folder
2. Click on map.exe
3. Receiver error

**Expected behavior**
The map application should open.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
Has happened on new install as well as after use.

**Comment by Valalol** [comment]
Hey CenteredAxis,
Try copying the folder `Images` located under `Navitool-win32-x64\resources\app\Images` into the main folder of the app called `Navitool-win32-x64` Then, it should work as intended.
Greetings,
Valalol

**Comment by CenteredAxis** [comment]
Worked perfectly! Thank you!

**Comment by Valalol** [comment]
Yep you have to give it some values to plot ^^
I recommend starting the main tool, doing like two `/showlocation` commands and then starting the map
Or else you can edit the values stored in the `Logs.csv` file for it to have at least one value since the last restart of the tool.

**Comment by Valalol** [comment]
That's what I tried to explain in the part 6 of the readme :
```If you want the tool to draw your location on a map, run the Map.exe and make sure you've done a few commands in-game. The map depends on the main tool to work.
```

**Comment by CenteredAxis** [comment]
I got it now, and thank you very much for the understanding. Thank you for your work! It's a great tool.
